export interface Prompt {
  id: number;
  category: string;
  text: string;
  descriptionKo: string;
}

export const prompts: Prompt[] = [
    // 1-20 Traditional (Dominican/Amargue)
    { id: 1, category: 'Traditional', text: 'Male (50s), Nasal, High-pitched, Bitter heartbreak (Amargue)', descriptionKo: '남성(50대), 비성(콧소리), 고음역대, 쓰라린 이별의 아픔(Amargue)' },
    { id: 2, category: 'Traditional', text: 'Older Male, Raw, Guitar-driven, Cabaret style', descriptionKo: '노년 남성, 다듬어지지 않은 거친 목소리, 기타 중심의 카바레 스타일' },
    { id: 3, category: 'Traditional', text: 'Male, Crying tone, Tremolo, Deep despair', descriptionKo: '남성, 울먹이는 톤, 떨림 창법, 깊은 절망감' },
    { id: 4, category: 'Traditional', text: 'Senior Male, Folkloric, Storytelling, Rural Dominican vibe', descriptionKo: '노년 남성, 민속적인 느낌, 이야기하듯 부르는, 도미니카 시골 감성' },
    { id: 5, category: 'Traditional', text: 'Male, Rapid-fire phrasing, Witty, Double entendre lyrics', descriptionKo: '남성, 빠른 프레이징, 재치 있고 이중적인 의미의 가사' },
    { id: 6, category: 'Traditional', text: 'Older Male, Gravelly, Passionate, Bar fight theme', descriptionKo: '노년 남성, 걸걸한 목소리, 열정적인, 술집 싸움 테마' },
    { id: 7, category: 'Traditional', text: 'Male, High Tenor, Sharp, Piercing Requinto accompaniment', descriptionKo: '남성, 하이 테너, 날카롭고 찌르는 듯한 레킨토(기타) 반주' },
    { id: 8, category: 'Traditional', text: 'Senior Male, Melancholic, Solitary, Drink in hand vibe', descriptionKo: '노년 남성, 우울한, 고독한, 술잔을 든 분위기' },
    { id: 9, category: 'Traditional', text: 'Male, Aggressive, Jealousy, Macho persona', descriptionKo: '남성, 공격적인, 질투심, 마초적인 페르소나' },
    { id: 10, category: 'Traditional', text: 'Older Male, Falsetto flips, Emotional, Old school Bolero-Bachata', descriptionKo: '노년 남성, 가성 뒤집기, 감정적인, 올드스쿨 볼레로-바차타' },
    { id: 11, category: 'Traditional', text: 'Male, Raspy, Street vendor style, Loud and proud', descriptionKo: '남성, 허스키한, 거리 상인 스타일, 크고 당당한 목소리' },
    { id: 12, category: 'Traditional', text: 'Senior Male, Vibrato-heavy, Classic 80s style', descriptionKo: '노년 남성, 바이브레이션이 강한, 클래식 80년대 스타일' },
    { id: 13, category: 'Traditional', text: 'Male, Whining tone (Estilo Llorón), Begging for love', descriptionKo: '남성, 징징거리는 듯한 톤(Estilo Llorón), 사랑을 구걸하는 느낌' },
    { id: 14, category: 'Traditional', text: 'Older Male, Deep Baritone, Serious, Warning message', descriptionKo: '노년 남성, 깊은 바리톤, 진지한, 경고하는 듯한 메시지' },
    { id: 15, category: 'Traditional', text: 'Male, Playful, Upbeat, Merengue de Guitarra influence', descriptionKo: '남성, 장난기 있는, 경쾌한, 기타 메렝게의 영향' },
    { id: 16, category: 'Traditional', text: 'Senior Male, Hoarse, Late night serenade', descriptionKo: '노년 남성, 쉰 목소리, 늦은 밤의 세레나데' },
    { id: 17, category: 'Traditional', text: 'Male, Dramatic, Spoken interludes, Theatrical', descriptionKo: '남성, 드라마틱한, 중간 내레이션, 연극적인 연출' },
    { id: 18, category: 'Traditional', text: 'Older Male, Soft but gritty, Memories of youth', descriptionKo: '노년 남성, 부드럽지만 거친, 젊은 날의 추억' },
    { id: 19, category: 'Traditional', text: 'Male, High energy, Shouting ad-libs, Party starter', descriptionKo: '남성, 높은 에너지, 소리치는 애드리브, 파티 시작 분위기' },
    { id: 20, category: 'Traditional', text: 'Senior Male, Authentic, Unpolished, Field recording vibe', descriptionKo: '노년 남성, 진정성 있는, 다듬어지지 않은, 현장 녹음 느낌' },
    // 21-40 Romantic (Urban/Modern)
    { id: 21, category: 'Romantic', text: 'Young Male (20s), Falsetto, Breathless, Urban Bachata', descriptionKo: '청년 남성(20대), 가성, 숨 가쁜 듯한 창법, 어반 바차타' },
    { id: 22, category: 'Romantic', text: 'Male, Silky Tenor, Spanglish, New York style', descriptionKo: '남성, 비단결 같은 테너, 스페인어-영어 혼용, 뉴욕 스타일' },
    { id: 23, category: 'Romantic', text: 'Female (20s), Whispy, Dreamy, Pop influence', descriptionKo: '여성(20대), 속삭이는 듯한, 꿈꾸는 듯한, 팝 음악 영향' },
    { id: 24, category: 'Romantic', text: 'Male, R&B runs, Smooth, Sentimental', descriptionKo: '남성, R&B 기교, 매끄러운, 감성적인 분위기' },
    { id: 25, category: 'Romantic', text: 'Duo (Male/Female), Harmonizing, Sweet, Love duet', descriptionKo: '남녀 듀엣, 화음, 달콤한, 사랑의 듀엣' },
    { id: 26, category: 'Romantic', text: 'Male, Romeo style, Soft spoken intro, King of Bachata vibe', descriptionKo: '남성, 로미오 산토스 스타일, 부드러운 도입부 내레이션, 바차타의 제왕 느낌' },
    { id: 27, category: 'Romantic', text: 'Female, Clear, Polished, Modern radio hit', descriptionKo: '여성, 맑고 세련된, 현대적인 라디오 히트곡 스타일' },
    { id: 28, category: 'Romantic', text: 'Male, High-pitched, Emotional plea, Sorry theme', descriptionKo: '남성, 고음역대, 감정적인 호소, 사과/후회 테마' },
    { id: 29, category: 'Romantic', text: 'Male, Deep & Sexy, Whispering, Bedroom vibe', descriptionKo: '남성, 깊고 섹시한, 속삭이는, 침실 분위기' },
    { id: 30, category: 'Romantic', text: 'Young Male, Boy band style, Catchy chorus, Teen throb', descriptionKo: '청년 남성, 보이밴드 스타일, 중독성 있는 코러스, 하이틴 스타 느낌' },
    { id: 31, category: 'Romantic', text: 'Female, Sensual, Mid-tempo, Elegant', descriptionKo: '여성, 관능적인, 미디엄 템포, 우아한' },
    { id: 32, category: 'Romantic', text: 'Male, Smooth, Synth-pad backing, Futuristic romantic', descriptionKo: '남성, 부드러운, 신디사이저 패드 배경, 미래지향적 로맨틱' },
    { id: 33, category: 'Romantic', text: 'Male, Acoustic pop vocal, Gentle, Wedding song', descriptionKo: '남성, 어쿠스틱 팝 보컬, 부드러운, 결혼식 축가 느낌' },
    { id: 34, category: 'Romantic', text: 'Female, Husky whisper, Intimate, Late night call', descriptionKo: '여성, 허스키한 속삭임, 친밀한, 심야 통화 느낌' },
    { id: 35, category: 'Romantic', text: 'Male, Prince Royce vibe, Sweet, Innocent love', descriptionKo: '남성, 프린스 로이스 스타일, 달콤한, 순수한 사랑' },
    { id: 36, category: 'Romantic', text: 'Duo (Male/Male), Rivalry, Trading verses, Love triangle', descriptionKo: '남남 듀엣, 라이벌 구도, 번갈아 부르기, 삼각관계 테마' },
    { id: 37, category: 'Romantic', text: 'Male, Autotune accents, Modern, Club ready', descriptionKo: '남성, 오토튠 포인트, 현대적인, 클럽 음악 스타일' },
    { id: 38, category: 'Romantic', text: 'Female, Powerful ballad style, Heartbreak, Resilience', descriptionKo: '여성, 파워풀한 발라드 스타일, 이별의 아픔, 극복' },
    { id: 39, category: 'Romantic', text: 'Male, Melodic, Guitar mimicking vocal, Catchy', descriptionKo: '남성, 멜로디가 강조된, 기타 소리를 따라 하는 보컬, 중독성 있는' },
    { id: 40, category: 'Romantic', text: 'Male, Sophisticated, Jazz chords, upscale vibe', descriptionKo: '남성, 세련된, 재즈 코드 진행, 고급스러운 분위기' },
    // 41-60 Diva
    { id: 41, category: 'Diva', text: 'Female (30s), Strong Belting, Dramatic, Cheating husband theme', descriptionKo: '여성(30대), 강한 벨팅 창법, 드라마틱한, 바람난 남편 테마' },
    { id: 42, category: 'Diva', text: 'Young Female, Sassy, Fast lyrics, Independent woman', descriptionKo: '젊은 여성, 당돌한, 빠른 가사, 독립적인 여성상' },
    { id: 43, category: 'Diva', text: 'Female, Deep Alto, Soulful, Torch song style', descriptionKo: '여성, 깊은 알토, 소울풀한, 짝사랑 노래 스타일' },
    { id: 44, category: 'Diva', text: 'Female, Flamenco vocal technique, Passionate, Spanish roots', descriptionKo: '여성, 플라멩코 창법, 열정적인, 스페인 뿌리' },
    { id: 45, category: 'Diva', text: 'Female, Breathless, Sexy, Dance floor anthem', descriptionKo: '여성, 숨 가쁜, 섹시한, 댄스 플로어 앤섬' },
    { id: 46, category: 'Diva', text: 'Female, Operatic touches, Grandiose, Epic love', descriptionKo: '여성, 오페라적 터치, 웅장한, 서사적인 사랑' },
    { id: 47, category: 'Diva', text: 'Middle-aged Female, Raspy, Experienced, Life advice', descriptionKo: '중년 여성, 허스키한, 경험이 묻어나는, 인생 조언' },
    { id: 48, category: 'Diva', text: 'Female, R&B runs, Complex melisma, Vocal showcase', descriptionKo: '여성, R&B 기교, 복잡한 멜리스마, 보컬 실력 과시' },
    { id: 49, category: 'Diva', text: 'Female, Soft & Airy -> Powerful Climax, Dynamic', descriptionKo: '여성, 부드럽고 공기 섞인 시작 -> 파워풀한 절정, 다이내믹한 전개' },
    { id: 50, category: 'Diva', text: 'Female, Urban flow, Rap-singing bridge, Swagger', descriptionKo: '여성, 어반 플로우, 랩과 노래의 중간인 브릿지, 스웨그' },
    { id: 51, category: 'Diva', text: 'Female, Tearful, Emotional breakdown, Acting vocal', descriptionKo: '여성, 눈물 섞인, 감정 폭발, 연기하는 듯한 보컬' },
    { id: 52, category: 'Diva', text: 'Female, Bright, Pop-star, Commercial sound', descriptionKo: '여성, 밝은, 팝스타, 대중적인 사운드' },
    { id: 53, category: 'Diva', text: 'Female, Dark, Mysterious, Femme Fatale', descriptionKo: '여성, 어두운, 미스터리한, 팜므파탈' },
    { id: 54, category: 'Diva', text: 'Female, Caribbean accent, rhythmic, Island vibe', descriptionKo: '여성, 카리브해 억양, 리듬감 있는, 섬 분위기' },
    { id: 55, category: 'Diva', text: 'Female, Sweet, Innocent, First love nostalgia', descriptionKo: '여성, 달콤한, 순수한, 첫사랑의 향수' },
    { id: 56, category: 'Diva', text: 'Female, Aggressive, Angry, Breakup song', descriptionKo: '여성, 공격적인, 분노에 찬, 이별 노래' },
    { id: 57, category: 'Diva', text: 'Female, Gospel influence, Spiritual, Uplifting', descriptionKo: '여성, 가스펠 영향, 영적인, 희망찬' },
    { id: 58, category: 'Diva', text: 'Female, Smooth Jazz tone, Lounge Bachata', descriptionKo: '여성, 스무스 재즈 톤, 라운지 바차타' },
    { id: 59, category: 'Diva', text: 'Female, High Whistle register, Impressive, Technical', descriptionKo: '여성, 초고음 휘슬 레지스터, 인상적인, 테크니컬한' },
    { id: 60, category: 'Diva', text: 'Female, Spanglish, International vibe, Crossover hit', descriptionKo: '여성, 스페인어-영어 혼용, 국제적인 분위기, 크로스오버 히트' },
    // 61-80 Fusion
    { id: 61, category: 'Fusion', text: 'Male, Autotune heavy, Trap beats, Bachata-Trap', descriptionKo: '남성, 강한 오토튠, 트랩 비트, 바차타-트랩' },
    { id: 62, category: 'Fusion', text: 'Female, Bossa Nova style, Soft, Bachata-Bossa', descriptionKo: '여성, 보사노바 스타일, 부드러운, 바차타-보사' },
    { id: 63, category: 'Fusion', text: 'Male, Reggaeton flow, Dembow rhythm, Bachatón', descriptionKo: '남성, 레게톤 플로우, 뎀보 리듬, 바차톤(Bachatón)' },
    { id: 64, category: 'Fusion', text: 'Group, Salsa style brass, High energy, Bachata-Salsa', descriptionKo: '그룹, 살사 스타일 브라스, 높은 에너지, 바차타-살사' },
    { id: 65, category: 'Fusion', text: 'Male, Rock voice, Electric guitar solo, Bachata-Rock', descriptionKo: '남성, 락 보컬, 일렉 기타 솔로, 바차타-락' },
    { id: 66, category: 'Fusion', text: 'Female, Tango accordion, Dramatic, Bachata-Tango', descriptionKo: '여성, 탱고 아코디언, 드라마틱한, 바차타-탱고' },
    { id: 67, category: 'Fusion', text: 'Male, Merengue speed, Fast, Bacharengue', descriptionKo: '남성, 메렝게 속도, 빠른, 바차렝게(Bacharengue)' },
    { id: 68, category: 'Fusion', text: 'Female, Electronic effects, Synth-pop, Cyber-Bachata', descriptionKo: '여성, 일렉트로닉 효과, 신스팝, 사이버-바차타' },
    { id: 69, category: 'Fusion', text: 'Male, Country twang, Slide guitar, Bachata-Country', descriptionKo: '남성, 컨트리 억양, 슬라이드 기타, 바차타-컨트리' },
    { id: 70, category: 'Fusion', text: 'Male, Rapping verses, Singing chorus, Hip-Hop Bachata', descriptionKo: '남성, 랩 벌스(Verse), 노래 코러스, 힙합 바차타' },
    { id: 71, category: 'Fusion', text: 'Female, Bolero pace, Slow, Romantic classic', descriptionKo: '여성, 볼레로 박자, 느린, 로맨틱 클래식' },
    { id: 72, category: 'Fusion', text: 'Male, Mariachi trumpet, Mexican style, Bachata-Ranchera', descriptionKo: '남성, 마리아치 트럼펫, 멕시코 스타일, 바차타-란체라' },
    { id: 73, category: 'Fusion', text: 'Female, K-Pop production, Polished, Korean-Latin mix', descriptionKo: '여성, K-Pop 프로덕션, 세련된, 한국-라틴 믹스' },
    { id: 74, category: 'Fusion', text: 'Male, Afro-beat percussion, Rhythmic, Afro-Bachata', descriptionKo: '남성, 아프로비트 퍼커션, 리듬감 있는, 아프로-바차타' },
    { id: 75, category: 'Fusion', text: 'Male, Classical guitar, Opera voice, Bachata-Classical', descriptionKo: '남성, 클래식 기타, 성악가 목소리, 바차타-클래식' },
    { id: 76, category: 'Fusion', text: 'Duo, Flamenco claps, Spanish guitar, Flamenco-Bachata', descriptionKo: '듀엣, 플라멩코 박수, 스패니시 기타, 플라멩코-바차타' },
    { id: 77, category: 'Fusion', text: 'Female, Lo-fi aesthetic, Chill, Bedroom Pop Bachata', descriptionKo: '여성, 로파이 미학, 차분한, 베드룸 팝 바차타' },
    { id: 78, category: 'Fusion', text: 'Male, Funk bass, Groovy, Bachata-Funk', descriptionKo: '남성, 펑크 베이스, 그루브한, 바차타-펑크' },
    { id: 79, category: 'Fusion', text: 'Male, Reggae chop, Laid back, Bachata-Reggae', descriptionKo: '남성, 레게 리듬, 여유로운, 바차타-레게' },
    { id: 80, category: 'Fusion', text: 'Female, Disco strings, Retro 70s, Disco-Bachata', descriptionKo: '여성, 디스코 스트링, 복고 70년대, 디스코-바차타' },
    // 81-100 Special
    { id: 81, category: 'Special', text: 'Male, Spoken Intro "Listen to the words...", Whisper', descriptionKo: '남성, 도입부 내레이션 "가사를 잘 들어봐...", 속삭임' },
    { id: 82, category: 'Special', text: 'Female, Phone call skit, Crying, "Why did you leave?"', descriptionKo: '여성, 전화 통화 연기, 울음, "왜 떠난 거야?"' },
    { id: 83, category: 'Special', text: 'Male, "So Nasty" ad-lib, Cheeky, Producer tag', descriptionKo: '남성, "So Nasty" 애드리브, 건방진, 프로듀서 태그' },
    { id: 84, category: 'Special', text: 'Group, Party noise background, "Put your hands up"', descriptionKo: '그룹, 파티 소음 배경, "손 머리 위로"' },
    { id: 85, category: 'Special', text: 'Male, Mimicking guitar solo with voice, Scatting', descriptionKo: '남성, 목소리로 기타 솔로 흉내, 스캣' },
    { id: 86, category: 'Special', text: 'Female, ASMR style, Very close mic, Intimate', descriptionKo: '여성, ASMR 스타일, 초근접 마이크, 친밀한' },
    { id: 87, category: 'Special', text: 'Male, DJ Hype man, Echo effects, Club announcement', descriptionKo: '남성, DJ 하이프 맨, 에코 효과, 클럽 안내방송' },
    { id: 88, category: 'Special', text: 'Male, Drunk singing, Slurring, Funny', descriptionKo: '남성, 취중 노래, 꼬인 발음, 재미있는' },
    { id: 89, category: 'Special', text: 'Female, Laughing while singing, Flirty, Joyful', descriptionKo: '여성, 웃으면서 노래하기, 유혹적인, 즐거운' },
    { id: 90, category: 'Special', text: 'Male, Heavy breathing, "I can\'t live without you"', descriptionKo: '남성, 거친 숨소리, "너 없인 못 살아"' },
    { id: 91, category: 'Special', text: 'Male, Falsetto scream "Ayyyy!", Traditional cry', descriptionKo: '남성, 가성 비명 "Ayyyy!", 전통적인 추임새' },
    { id: 92, category: 'Special', text: 'Female, Acapella start, No music, Pure voice', descriptionKo: '여성, 아카펠라 시작, 무반주, 순수한 목소리' },
    { id: 93, category: 'Special', text: 'Male, Beatboxing Bachata rhythm, Vocal percussion', descriptionKo: '남성, 바차타 리듬 비트박스, 보컬 퍼커션' },
    { id: 94, category: 'Special', text: 'Male, Dark villain voice, Low pitch, Spooky', descriptionKo: '남성, 어두운 악당 목소리, 저음, 으스스한' },
    { id: 95, category: 'Special', text: 'Female, Child-like voice, Innocent, Lullaby', descriptionKo: '여성, 아이 같은 목소리, 순수한, 자장가' },
    { id: 96, category: 'Special', text: 'Male, Fast rapping instruction, Dance moves', descriptionKo: '남성, 빠른 랩 스타일 설명, 춤 동작 지시' },
    { id: 97, category: 'Special', text: 'Male, Robot voice effect, Sci-fi theme', descriptionKo: '남성, 로봇 목소리 효과, SF 테마' },
    { id: 98, category: 'Special', text: 'Female, Siren call, Melodic vocalization (No words)', descriptionKo: '여성, 사이렌(요정)의 부름, 멜로디 허밍 (가사 없음)' },
    { id: 99, category: 'Special', text: 'Male, "Romeo... you need this", Dedication intro', descriptionKo: '남성, "로미오... 이게 필요할 거야", 헌정 멘트' },
    { id: 100, category: 'Special', text: 'Male/Female, Fade out conversation, "I love you", Ending', descriptionKo: '남녀, 페이드 아웃 대화, "사랑해", 엔딩' },
  ];